"use server";

import { NextRequest, NextResponse } from "next/server";

interface EventItem {
    id: string;        // generated by backend
    date: number;
    suffix: string;
    month: string;
    year: number;
    time: string;
    location: string;
    eventTitle: string;
    createdAt: string;
  }
  
export async function POST(req: NextRequest) {
    const body = await req.json();

    const { date, suffix, month, year, time, location, eventTitle } = body;
    const {data, error} = 
}
